### ISSUE TITLE
Concern with LICENSE

### ISSUE THREAD

**Issue by lefnire** [realpython/flask-jwt-auth#13]
So normally MIT / GPL is applied to a module / plugin. Drop those into your project and it's not derivative works but a dependency, allowing developers to use open source in their projects yet still house IP. This project isn't a module (yet? does using Blueprint portend a module future?). The consequence is clone-and-modify this project, kinda the only way at present, certainly makes a derivative work - meaning our projects are stuck MIT and open. Incidentally I do plan open-sourcing something I'm working on, but AGPL; though I'm sure many plan to use this project as a quickstart boilerplate for closed IP. Any thoughts on this?

**Comment by mjhea0** [comment]
This project was never intended be a module/[exention](http://flask.pocoo.org/docs/0.12/extensiondev/). You wouldn't want to use it in production either. Check out https://github.com/vimalloc/flask-jwt-extended for an actual extension that is ready for production.

Hope that helps.
