### ISSUE TITLE
'/auth/status' error

### ISSUE THREAD

**Issue by AliShirzad** [realpython/flask-jwt-auth#9]
```
auth_token = auth_header.split(" ")[1]
IndexError: list index out of range
```  

**auth_header** is one piece so splitting it and taking the second part raises "_IndexError: list index out of range_" error.

**Comment by mjhea0** [comment]
When does the bearer token not follow this format?

`Bearer <token>`

**Comment by AliShirzad** [comment]
Before decoding the auth_token

````
    def get(self):
        # get the auth token
        auth_header = request.headers.get('Authorization')
        if auth_header:
            auth_token = auth_header.split(" ")[1]
        else:
            auth_token = ''
        if auth_token:
            resp = User.decode_auth_token(auth_token)

**Comment by mjhea0** [comment]
Yes. Can you show me an example header where this is breaking?

**Comment by AliShirzad** [comment]
![screen shot 1396-05-11 at 18 19 43](https://user-images.githubusercontent.com/9092949/28876674-36ee8694-77af-11e7-91f0-543bca401436.png)

Is this what you mean?

**Comment by mjhea0** [comment]
The token is malformed. In the value you need to put `Bearer ` before the token value.

`Bearer 12345` 

I updated the code to catch this. I'll update the blog post later today or tomorrow.  

https://github.com/realpython/flask-jwt-auth/pull/10

**Comment by mjhea0** [comment]
Merged https://github.com/realpython/flask-jwt-auth/pull/10 and updated the blog post. 

https://realpython.com/blog/python/token-based-authentication-with-flask/

Thanks again!
